### PR TITLE
Case 29287 - use default strategy for static assets compilation

### PR DESCRIPTION
**Pull request by elevinskii-aonach**

### CODE REVIEW

**Comment by elevinskii-aonach** [comment]
> I had a comment on this about maybe versioning it so it wouldn't get applied to everyone immediately and we could control the flow. @AaronONeill will follow up as well on it.

No problem at all. We're able to use any branch of the workflow in the `deploy.yml` inside any project. But are you sure it won't turn to total mess in future when we can't remember why we're using the custom branch (or forget to merge the branch to master at the end)?

**Comment by joesken** [comment]
> > I had a comment on this about maybe versioning it so it wouldn't get applied to everyone immediately and we could control the flow. @AaronONeill will follow up as well on it.
> 
> No problem at all. We're able to use any branch of the workflow in the `deploy.yml` inside any project. But are you sure it won't turn to total mess in future when we can't remember why we're using the custom branch (or forget to merge the branch to master at the end)?

I don't know tbh. So maybe better explain what I'm trying to solve.  I would prefer that all deployments all of a sudden didn't change their static:content strategies without some oversight.  My vauge ideas was to solve that via different versions by pulling in a different composer relase version (not even sure if this is correct/possible). Then we can migrate to the new version client by client as we wish. Same as what you are saying I think in a roundabout way.

I suppose after all that the answer is probably "yes", albeit making it messy I think it would be better to drip feed out the change. 

@elevinskii-aonach does that make (kinda) sense?
@AaronONeill do you have a view on it?

**Comment by AaronONeill** [comment]
@joesken @elevinskii-aonach 

If we have the ability to push this out only to some projects for the moment then I think we should. Until we're confident we're happy with it. As long as we keep a record of the projects where we've moved away from the current default then I don't think it will be that messy. 

Perhaps another way to handle this, is if we were somehow able to set a "deployment mode" flag. If the flag was set, then it would run the full static content deploy. Otherwise, if no flag was set then default to the compact strategy. No idea if this is possible, but might be less messy and would mean we could turn it on/off for projects as we see fit.

**Comment by elevinskii-aonach** [comment]
@joesken @elevinskii-aonach 

I like the idea to keep moving forward release by release - that makes much sense in my view.

Just created the latest release by last master commit - v1.1.12, and what I'm going to do:
- adjust `deploy.yml` configs for all M2 projects where Github Actions deployments are used to use this strict version of the workflow (now `dev-master` used, means downloading from master branch)
- merge the current PR and create new release, v1.1.13
- use new version where we can (only for M&B for now)

All right?

> Perhaps another way to handle this, is if we were somehow able to set a "deployment mode" flag. If the flag was set, then it would run the full static content deploy. Otherwise, if no flag was set then default to the compact strategy. No idea if this is possible, but might be less messy and would mean we could turn it on/off for projects as we see fit.

The idea with the flag is quite good (and definitely will work!), but I'm worried it would be unneeded complication of the logic - not sure where the flag could be used - to be honest, I haven't met situations yet where the compact strategy (or any others) _is required_.

I'd propose the moves release by release (as described above) - let me know your thoughts, Aaron & Joseph, thanks!

**Comment by joesken** [comment]
> @joesken @elevinskii-aonach
> 
> I like the idea to keep moving forward release by release - that makes much sense in my view.
> 
> Just created the latest release by last master commit - v1.1.12, and what I'm going to do:
> 
> * adjust `deploy.yml` configs for all M2 projects where Github Actions deployments are used to use this strict version of the workflow (now `dev-master` used, means downloading from master branch)
> * merge the current PR and create new release, v1.1.13
> * use new version where we can (only for M&B for now)
> 
> All right?
> 
> > Perhaps another way to handle this, is if we were somehow able to set a "deployment mode" flag. If the flag was set, then it would run the full static content deploy. Otherwise, if no flag was set then default to the compact strategy. No idea if this is possible, but might be less messy and would mean we could turn it on/off for projects as we see fit.
> 
> The idea with the flag is quite good (and definitely will work!), but I'm worried it would be unneeded complication of the logic - not sure where the flag could be used - to be honest, I haven't met situations yet where the compact strategy (or any others) _is required_.
> 
> I'd propose the moves release by release (as described above) - let me know your thoughts, Aaron & Joseph, thanks!

That sounds perfect to me - please go ahead.

**Pull request merged**
